[package]
name = "foxchain"
version = "0.2.2"
authors = ["LSH <github@lsh.tech>"]
edition = "2021"
description = "Multi-chain blockchain address identification and analysis library"
license = "GPL-3.0"


[dependencies]
